teleop:
    movement:
        type: topic
        message_type: geometry_msgs/Twist
        topic_name: cmd_vel
        deadman_buttons: [0]
        axis_mappings:
            -
                axis: 1
                target: linear.x
                scale: 1.0
                offset: 0.00
            -
                axis: 2
                target: angular.z
                scale: 1.0
                offset: 0.00
            -
                axis: 0
                target: linear.y
                scale: 1.0
                offset: 0.00
